service: ui-waf-log-assoc

frameworkVersion: "3"

plugins:
  - serverless-plugin-scripts
  - serverless-s3-bucket-helper

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

custom:
  stage: ${opt:stage, self:provider.stage}
  iamPath: ${env:IAM_PATH, "/"}
  wafAclArn: ${cf:ui-${self:custom.stage}.CloudFrontWebAclArn}
  firehoseStreamArn: ${cf:ui-${self:custom.stage}.FirehoseArn}
  scripts:
    hooks:
      # Associate the Firehose and the WAF Acl
      deploy:finalize: |
        aws wafv2 put-logging-configuration \
          --logging-configuration ResourceArn=${self:custom.wafAclArn},LogDestinationConfigs=${self:custom.firehoseStreamArn} \
          --region ${self:provider.region}
