version: "2"
checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 15
  return-statements:
    enabled: false
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/*.test.js"