version: 2.0

jobs:
  deploy:
    executor:
      docker:
        - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: set environment for deploy
          command: |
            # Environment variable names cannot contain hyphens
            # So here we take the branch name, swap hyphens for underscores, and set variables if they exist.
            echo "export ROUTE_53_HOSTED_ZONE_ID=\$${CIRCLE_BRANCH//-/_}_ROUTE_53_HOSTED_ZONE_ID" >> $BASH_ENV
            echo "export ROUTE_53_DOMAIN_NAME=\$${CIRCLE_BRANCH//-/_}_ROUTE_53_DOMAIN_NAME" >> $BASH_ENV
            echo "export CLOUDFRONT_CERTIFICATE_ARN=\$${CIRCLE_BRANCH//-/_}_CLOUDFRONT_CERTIFICATE_ARN" >> $BASH_ENV
            echo "export CLOUDFRONT_DOMAIN_NAME=\$${CIRCLE_BRANCH//-/_}_CLOUDFRONT_DOMAIN_NAME" >> $BASH_ENV
            echo "export INFRASTRUCTURE_TYPE=\$${CIRCLE_BRANCH//-/_}_INFRASTRUCTURE_TYPE" >> $BASH_ENV
      - run: sudo npm install -g serverless
      - run:
          name: deploy database
          no_output_timeout: 30m
          command: |
            cd services/database
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy uploads
          no_output_timeout: 30m
          command: |
            cd services/uploads
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy app-api
          no_output_timeout: 30m
          command: |
            cd services/app-api
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy elasticsearch-auth
          no_output_timeout: 30m
          command: |
            cd services/elasticsearch-auth
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy elasticsearch
          no_output_timeout: 30m
          command: |
            cd services/elasticsearch
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy stream-functions
          no_output_timeout: 30m
          command: |
            cd services/stream-functions
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy ui-auth
          no_output_timeout: 30m
          command: |
            cd services/ui-auth
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy ui
          no_output_timeout: 30m
          command: |
            cd services/ui
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: deploy ui-src
          no_output_timeout: 30m
          command: |
            cd services/ui-src
            npm install
            serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: Print the application endpoint
          command: |
            cd services
            ./output.sh ui CloudFrontEndpointUrl $CIRCLE_BRANCH

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - /^cci-[a-zA-Z0-9-]*$/ # Branch begins with cci- and only contains letters, numbers, and hyphens
