service: email

frameworkVersion: "3"

useDotenv: true

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-s3-bucket-helper
  - serverless-offline
custom:
  stage: ${opt:stage, self:provider.stage}
  iamPath: ${ssm:/configuration/${self:custom.stage}/iam/path, ssm:/configuration/default/iam/path}
  iamPermissionsBoundaryPolicy: ${ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy, ssm:/configuration/default/iam/permissionsBoundaryPolicy, ""}
  oneMacTableName: ${cf:app-api-${self:custom.stage}.OneMacTableName, ""}
  oneMacTableArn: ${cf:app-api-${self:custom.stage}.OneMacTableArn, ""}
  emailTopic: ${cf:app-api-${self:custom.stage}.EmailTopic, ""}
  emailEventTopic: ${cf:app-api-${self:custom.stage}.EmailEventTopic, ""}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  timeout: 600
  role: LambdaEmailEventRole
  environment:
    NODE_OPTIONS: "--enable-source-maps"
    oneMacTableName: ${self:custom.oneMacTableName}
    configurationSetName: 'email-${self:custom.stage}'
  iam:
    role:
      path: ${self:custom.iamPath}
      permissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy${self:custom.iamPermissionsBoundaryPolicy, ""}'

functions:
  processEmails:
    handler: handlers/processEmails.main
    events:
      - schedule:
          rate: rate(30 minutes)

  processEmailEvents:
    handler: handlers/processEmailEvents.main
    events:
      - sns: ${self:custom.emailEventTopic}

resources:
  Conditions:
    CreatePermissionsBoundary:
      Fn::Not:
        - Fn::Equals:
          - ""
          - ${self:custom.iamPermissionsBoundaryPolicy}

  Resources:
    EmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: ${self:custom.emailTopic}
        Endpoint: !GetAtt ProcessEmailsLambdaFunction.Arn
        Protocol: lambda

    EmailEventSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: ${self:custom.emailEventTopic}
        Endpoint: !GetAtt ProcessEmailEventsLambdaFunction.Arn
        Protocol: lambda

    EmailEventConfigurationSet:
      Type: AWS::SES::ConfigurationSet
      Properties:
        Name: 'email-${self:custom.stage}'

    EmailEventConfigurationSetEventDestination:
      Type: AWS::SES::ConfigurationSetEventDestination
      Properties:
        ConfigurationSetName: !Ref EmailEventConfigurationSet
        EventDestination: 
          Enabled: true
          Name: 'email-${self:custom.stage}'
          MatchingEventTypes:
            - "send"
            - "reject"
            - "bounce"
            - "complaint"
            - "delivery"
            - "open"
            - "click"
            - "renderingFailure"
            - "deliveryDelay"
            - "subscription"
          SnsDestination: 
            TopicARN: ${self:custom.emailEventTopic}

    LambdaEmailEventRole: # Why isn't this with the function as an iamRoleStatements?  https://github.com/serverless/serverless/issues/6485
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
        Path: ${self:custom.iamPath}
        PermissionsBoundary:
          Fn::If:
            - CreatePermissionsBoundary
            - Fn::Join:
              - ''
              -
                - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - ':policy'
                - '${self:custom.iamPermissionsBoundaryPolicy}'
            - Ref: AWS::NoValue
        Policies:
          - PolicyName: 'LambdaRolePolicy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: 'Allow'
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: "Allow"
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: arn:aws:dynamodb:*:*:table/${self:custom.oneMacTableName}
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.oneMacTableName}/index/*
