# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: ui-auth

custom:
  stage: ${opt:stage, self:provider.stage}
  attachments_bucket_arn: ${cf:uploads-${self:custom.stage}.AttachmentsBucketArn}
  api_gateway_rest_api_name: ${cf:app-api-${self:custom.stage}.ApiGatewayRestApiName}
  application_endpoint_url: ${cf:ui-${self:custom.stage}.ApplicationEndpointUrl}
  okta_metadata_url: ${env:OKTA_METADATA_URL}
  iamPath: ${env:IAM_PATH, "/"}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

resources:
  Conditions:
    isVal: { "Fn::Equals": ["${self:custom.stage}", "master"] }
    isDev: { "Fn::Equals": ["${self:custom.stage}", "develop"] }
    isValOrDev:
      { "Fn::Or": [{ "Condition": "isProd" }, { "Condition": "isRC" }] }
    CreatePermissionsBoundary:
      Fn::Not:
        - Fn::Equals:
            - ""
            - ${env:IAM_PERMISSIONS_BOUNDARY_POLICY, ""}

  Resources:
    BasicParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:custom.stage}/nightwatch/TEST_STATE_SUBMITTER_USERS
        Type: String
        Value:
          - Fn::If:
              - isDev
              - MOSESPA01
          - Fn::If:
              - isVal
              - WYSESPA1
          - Fn::Not:
              - isValOrDev
              - statesubmitteractive@cms.hhs.local
          - Fn::GetAtt:
              - NightWatchUser
              - Outputs.NightWatchUser

  Outputs:
    NightWatchUserName:
      Value:
        - Fn::GetAtt:
            - NightWatchUser
            - Outputs.NightWatchUser
