Resources:
  # Topic and Event Rule for API Lambda timeouts
  ApiLambdaErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for Monitoring OneMac API lambda errors
  ApiLambdaErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:custom.stage}-timeout-ErrorAlarm
        AlarmDescription: Alarm triggered when any Lambda function in the current stage has an error
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !GetAtt timeout.Arn
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        AlarmActions:
          - !Ref ApiLambdaErrorTopic