Resources:
  EmailEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Email-Events-${self:service}-${sls:stage}
      DisplayName: Monitoring the sending of emails
#      KmsMasterKeyId: alias/aws/sns

  EmailEventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ses.amazonaws.com
            Action: 
              - sns:Subscribe
              - sns:Publish
            Resource: !Ref EmailEventTopic
      Topics:
        - !Ref EmailEventTopic

Outputs:
  EmailEventTopic:
    Value: !Ref EmailEventTopic
