Resources:
  EmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Emails-${self:service}-${sls:stage}
      DisplayName: Distributing the sending of emails
      KmsMasterKeyId: alias/aws/sns

  EmailTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 
              - sns:Publish
              - sns:Subscribe
            Resource: !Ref EmailTopic
      Topics:
        - !Ref EmailTopic

  EmailEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Email-Events-${self:service}-${sls:stage}
      DisplayName: Monitoring the sending of emails
#      KmsMasterKeyId: alias/aws/sns

  EmailEventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ses.amazonaws.com
            Action: 
              - sns:Subscribe
              - sns:Publish
            Resource: !Ref EmailEventTopic
      Topics:
        - !Ref EmailEventTopic

  EmailEventConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: 'Email-Config-${self:custom.stage}'

Outputs:
  EmailTopic:
    Value: !Ref EmailTopic
  EmailEventTopic:
    Value: !Ref EmailEventTopic
  EmailEventConfigurationSet:
    Value: !Ref EmailEventConfigurationSet
