Resources:
  # Topic and Event Rule for API Lambda timeouts
  OneMacApiLambdaErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for Monitoring OneMac API lambda errors
  OneMacApiLambdaErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:custom.stage}-ErrorAlarm
        AlarmDescription: Alarm triggered when any Lambda function in the current stage has an error
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Sub '${self:service}-${self:custom.stage}-*'
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        AlarmActions:
          - !Ref OneMacApiLambdaErrorTopic