Resources:
  #  This is really a submissions table... keeping "pure" for now because it is in production
  AmendmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
          # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  SpaIdTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.spaIdTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
Outputs:
  AmendmentsTableStreamArn:
    Value: !GetAtt AmendmentsTable.StreamArn
  SpaIdTableName:
    Value: !Ref SpaIdTable
  SpaIdTableArn:
    Value: !GetAtt SpaIdTable.Arn
