Resources:
  CmsSpaFormFromEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: StringList
      Description: Branch specific email address of sender for cms spa form submission emails
      Name: !Sub /configuration/${self:custom.stage}/email/cms_spa_form_from_email
      Value: "spa-reply@cms.hhs.gov"

  CmsUserAccessFromEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: StringList
      Description: Branch specific email address of sender for cms user access emails
      Name: !Sub /configuration/${self:custom.stage}/email/cms_user_access_from_email
      Value: "OneMACAccess@cms.hhs.gov"

  CmsSpaFormCmsEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: StringList
      Description: Branch specific email address of recipient for cms spa form submission emails
      Name: !Sub /configuration/${self:custom.stage}/email/cms_spa_form_cms_email
      Value: "\"OSG\" <OneMAC@cms.hhs.gov>"

  CmsSpaFormChipEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: StringList
      Description: Branch specific email address of recipient for cms chip spa form submission emails
      Name: !Sub /configuration/${self:custom.stage}/email/cms_spa_form_chip_email
      Value: "\"CHIP to\" <OneMAC@cms.hhs.gov>"

  CmsSpaFormChipCcEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: Branch specific email addresses of recipients for CC on cms chip spa form submission emails
      Name: !Sub /configuration/${self:custom.stage}/email/cms_chip_form_cc_email
      Value: "\"CHIP cc List\" <OneMAC@cms.hhs.gov>"

  CmsDpoEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: Branch specific email addresses of the DPO group for CMS
      Name: !Sub /configuration/${self:custom.stage}/email/cms_dpo_email
      Value: "\"DPO group\" <OneMAC@cms.hhs.gov>"

  CmsDmcoEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: Branch specific email addresses of the DMCO group for CMS
      Name: !Sub /configuration/${self:custom.stage}/email/cms_dmco_email
      Value: "\"DMCO group\" <OneMAC@cms.hhs.gov>"

  CmsDhcbsooEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: Branch specific email addresses of the DHCBSOO group for CMS
      Name: !Sub /configuration/${self:custom.stage}/email/cms_dhcbsoo_email
      Value: "\"DHCBSOO group\" <OneMAC@cms.hhs.gov>"