Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
    # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
