Resources:
  StateUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stateUserTableName}
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
    # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  StateAdminTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stateAdminTableName}
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
    # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
