# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: uploads

plugins:
  - serverless-s3-local
  - serverless-offline

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

custom:
  stage: ${opt:stage, self:provider.stage}
  # S3 offline configuration
  s3:
    host: localhost
    directory: /tmp
    cors: resources/local-cors-policy.xml

resources:
  Resources:
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
        #Set at rest encryption
        BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
    # Policy to allow public read access to all attachments
    S3CMSReadBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: AttachmentsBucket
        PolicyDocument:
          Statement:
            - Effect: 'Allow'
              Action: 
                - 's3:GetObject'
              Principal: '*'
              Resource: 
                Fn::Join: 
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: AttachmentsBucket
                    - '/protect/*'

  # Print out the name of the bucket that is created
  Outputs:
    AttachmentsBucketName:
      Value:
        Ref: AttachmentsBucket
    AttachmentsBucketArn:
      Value: !GetAtt AttachmentsBucket.Arn
    Region:
      Value:
        Ref: AWS::Region
