name: Deploy

concurrency: ci-${{ github.ref }}

on:
  push:
    branches:
      - "*"
      - "!skipci*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: |
          npm ci
          for service in services/*/; do
            pushd "$service"
            if [ -f package-lock.json ]; then npm ci; fi
            popd
          done
      - name: Run ESLint
        run: npx eslint --max-warnings=0 services
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Unit Test & Publish Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          debug: true
          coverageCommand: ./unit-test.sh
          coverageLocations: |
            ${{github.workspace}}/services/*/coverage/lcov.info:lcov
  deploy:
    name: Deploy
    needs:
      - lint
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: set branch_name
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Check branch name is a legal serverless stage name
        run: |
          if [[ ! $branch_name =~ ^[a-z][a-z0-9-]*$ ]] || [[ $branch_name -gt 128 ]]; then
            echo """
              ------------------------------------------------------------------------------------------------------------------------------
              ERROR:  Please read below
              ------------------------------------------------------------------------------------------------------------------------------
              Bad branch name detected; cannot continue.

              The Serverless Application Framework has a concept of stages that facilitate multiple deployments of the same service.
              In this setup, the git branch name gets passed to Serverless to serve as the stage name.
              The stage name (branch name in this case) is tacked onto the end of the service name by Serverless.
              Therefore, the branch name must be a valid service name.

              From Serverless:
                A service name should only contain alphanumeric (case sensitive) and hyphens. It should start with an alphabetic character and shouldnt exceed 128 characters.

              For Github Actions support, please push your code to a new branch with a name that meets Serverless' service name requirements.
              So, make a new branch with a name that begins with a letter and is made up of only letters, numbers, and hyphens... then delete this branch.
              ------------------------------------------------------------------------------------------------------------------------------
            """
            exit 1
          fi
      - uses: actions/checkout@v1
      - name: set branch specific variable names
        run: ./.github/build_vars.sh set_names
      - name: set variable values
        run: ./.github/build_vars.sh set_values
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_ACCESS_KEY_ID] || secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_SECRET_ACCESS_KEY] || secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
          INFRASTRUCTURE_TYPE: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_INFRASTRUCTURE_TYPE] || secrets.INFRASTRUCTURE_TYPE || 'development' }}
          CMS_SPA_FORM_FROM_EMAIL: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_CMS_SPA_FORM_FROM_EMAIL] || secrets.CMS_SPA_FORM_FROM_EMAIL }}
          CMS_SPA_FORM_CMS_EMAIL: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_CMS_SPA_FORM_CMS_EMAIL] || secrets.CMS_SPA_FORM_CMS_EMAIL }}
          CMS_CHIP_FORM_CMS_EMAIL: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_CMS_CHIP_FORM_CMS_EMAIL] || secrets.CMS_CHIP_FORM_CMS_EMAIL }}
          BIGMAC_NAME: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_BIGMAC_NAME] || secrets.BIGMAC_NAME }}
          ROUTE_53_HOSTED_ZONE_ID: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_ROUTE_53_HOSTED_ZONE_ID] }}
          ROUTE_53_DOMAIN_NAME: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_ROUTE_53_DOMAIN_NAME] }}
          CLOUDFRONT_CERTIFICATE_ARN: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_CLOUDFRONT_CERTIFICATE_ARN] }}
          CLOUDFRONT_DOMAIN_NAME: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_CLOUDFRONT_DOMAIN_NAME] }}
          IAM_PATH: ${{ secrets.IAM_PATH }}
          IAM_PERMISSIONS_BOUNDARY_POLICY: ${{ secrets.IAM_PERMISSIONS_BOUNDARY_POLICY }}
          STAGE_PREFIX: ${{ secrets.STAGE_PREFIX }}
          METRICS_USERS: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_METRICS_USERS] || secrets.METRICS_USERS }}
          OKTA_METADATA_URL: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_OKTA_METADATA_URL] || secrets.OKTA_METADATA_URL }}
          COGNITO_TEST_USERS_PASSWORD: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_COGNITO_TEST_USERS_PASSWORD] || secrets.COGNITO_TEST_USERS_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Combine package-lock.json files to single file
        run: find services -maxdepth 3 -name package-lock.json | xargs cat package-lock.json > combined-package-lock.txt
      - name: cache service dependencies
        uses: actions/cache@v2
        with:
          path: |
            services/uploads/node_modules
            services/app-api/node_modules
            services/stream-functions/node_modules
            services/ui/node_modules
            services/ui-auth/node_modules
            services/ui-src/node_modules
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('combined-package-lock.txt') }}
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: Set dev login flag for all but production branch
        if: ${{ env.branch_name != 'production' }}
        run: echo "ALLOW_DEV_LOGIN=true" >> $GITHUB_ENV
      - name: Set testing email address unless in prod
        if: ${{ env.branch_name != 'production' }}
        run: echo "TESTING_TEAM_EMAIL=macproemailnotification@gmail.com" >> $GITHUB_ENV
      - name: deploy
        run: |
          # When deploying multiple copies of this quickstart to the same AWS Account (not ideal), a prefix helps prevent stepping on each other.
          # This can optionally be set as a variable in GitHub Actions Secrets
          ./deploy.sh $STAGE_PREFIX$branch_name
      - name: Seed Data
        # this "resets" any data explicitly provided in the seed files to what
        # is in the committed code
        if: ${{ env.branch_name != 'production' && env.branch_name != 'master' }}
        env:
          SLS_DEBUG: 'true'
          BRANCH: ${{ env.STAGE_PREFIX }}${{ env.branch_name }}
        run: cd services/app-api && serverless dynamodb seed --stage=$BRANCH --region=$AWS_DEFAULT_REGION --seed=domain --online
      - name: Load Test Users
        if: ${{ env.branch_name != 'production' && env.branch_name != 'master' }}
        run: ./loadTestUsers.py $STAGE_PREFIX$branch_name
      - name: Migrate Data
        run: cd ./services/app-api && sls invoke -s $STAGE_PREFIX$branch_name -f migrate
  cypress-test:
    name: Cypress Tests
    needs: deploy
    if: ${{ github.ref != 'refs/heads/production' && github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers:
          [
            OY2_3900_SPA_Waivers_FormatTest.spec.feature,
            OY2_4807_Validate_Waiver_Form_Logic.spec.feature,
            OY2_5868_Submission_List_Verification.spec.feature,
            OY2_5869_FileUpload_Attachment_Types.spec.feature,
            OY2_7522_Verify_Invalid_CHIP_SPAID_Message.spec.feature,
            OY2_8618_CMS_Approver.spec.feature,
            OY2_8618_CMS_System_Admin.spec.feature,
            OY2_9990_State_Submitter_Profile_Screen_Enhancements.spec.feature,
            OY2_9990_State_System_Admin_Profile_Screen_Enhancements.spec.feature,
            OY2_10093_Helpdesk_User.spec.feature,
            OY2_11149_Submission_Dashboard_Search_bar.spec.feature,
            OY2_11159_Case_sensitive_emails_causing_login_error.spec.feature,
            OY2_11469_Display_State_column_for_the_CMS_System_Admin.spec.feature,
            OY2_11581_Add_an_Expiration_Date_Column_to_the_Package_Dashboard_part2.spec.feature,
            OY2_11581_Add_an_Expiration_Date_Column_to_the_Package_Dashboard_part3.spec.feature,
            OY2_11581_Add_an_Expiration_Date_Column_to_the_Package_Dashboard.spec.feature,
            OY2_11676_Package_Dashboard_New_Waiver_tab_layout.spec.feature,
            OY2_11950_State_should_not_be_able_to_withdraw_a_package_in_OneMAC_in_Specific_statuses.spec.feature,
            OY2_12297_Home_Page_Update_Include_guidance_for_CMS_User.spec.feature,
            OY2_12596_CMSUserDenied.spec.feature,
            OY2_12596_CMSUserRevoked.spec.feature,
            OY2_12642 _Update_Text_on_FAQ_Page.spec.feature,
            OY2_12735_Additional_90th_Day_statuses_for_the_Package_Dashboard.spec.feature,
            OY2_13092_Package_Dashboard_Filter.spec.feature,
            OY2_13094_Package_Dashboard_Filter_By_State.spec.feature,
            OY2_13095_Package_Dashboard_Column_Picker.spec.feature,
            OY2_13517_FAQ_Page_Update_Host_Onboarding_and_Quickstart_docs_material.spec.feature,
            OY2_14464_Package_Dashboard_Separate_Tab_for_Waivers_and_SPAs.spec.feature,
            OY2_15426_Package_Dashboard_Waiver_Family_Column_for_the_Waivers_tab.spec.feature,
            OY2_15620_Updated_SPA_Package_Details_View_Card_View_with_Actions.spec.feature,
            OY2_15647_State_User_can_Respond_to_RAI.spec.feature,
            OY2_16294_Withdraw_action_on_waiver_component.spec.feature,
            OY2-11116_Package_Dashboard_Updates_90th_Day_Data_from_SEATool.spec.feature,
            OY2-12679_Users_can_request_a_role_change_in_OneMAC.spec.feature,
            OY2-13093_Submission_Dashboard_Filter_options_that_include_Dates.spec.feature,
            OY2-13234_CHIP_SPA_RAI.spec.feature,
            OY2-13234_Waiver_RAI.spec.feature,
            OY2_16347_Temporary_Extension_form_validations.spec.feature,
            OY2_16029_Submission_Form_Submit_button_updates_and_Warning_Text.spec.feature,
            OY2_16471_State_should_not_be_able_to_withdraw_RAI_Responses_in_OneMAC.spec.feature,
            OY2_14656_Left_Hand_Navigation_for_Package_Details_View.spec.feature,
            OY2_16322_RAI_Response_for_SPA_package_view.spec.feature,
            OY2_16707_CMS_Users_Denied_a_CRA_Role_loses_Read_Only_Access_to_OneMAC.spec.feature,
            OY2_15984_Updated_SPA_Package_Details_View_Additional_Information_Page.spec.js,
          ]
    steps:
      - name: set branch_name
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: set branch specific variable names
        run: ./.github/build_vars.sh set_names
      - name: set variable values
        run: ./.github/build_vars.sh set_values
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_ACCESS_KEY_ID] || secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_SECRET_ACCESS_KEY] || secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
          INFRASTRUCTURE_TYPE: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_INFRASTRUCTURE_TYPE] || secrets.INFRASTRUCTURE_TYPE || 'development' }}
          STAGE_PREFIX: ${{ secrets.STAGE_PREFIX }}
          COGNITO_TEST_USERS_PASSWORD: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_COGNITO_TEST_USERS_PASSWORD] || secrets.COGNITO_TEST_USERS_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Combine package-lock.json files to single file
        run: find services -maxdepth 3 -name package-lock.json | xargs cat package-lock.json > combined-package-lock.txt
      - name: cache service dependencies
        uses: actions/cache@v2
        with:
          path: |
            services/uploads/node_modules
            services/app-api/node_modules
            services/stream-functions/node_modules
            services/ui/node_modules
            services/ui-auth/node_modules
            services/ui-src/node_modules
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('combined-package-lock.txt') }}
      - name: Install dependencies
        run: npm ci
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: Endpoint
        run: |
          pushd services
          export APPLICATION_ENDPOINT=`./output.sh ui ApplicationEndpointUrl $STAGE_PREFIX$branch_name`
          echo "APPLICATION_ENDPOINT=$APPLICATION_ENDPOINT" >> $GITHUB_ENV
          echo "Application endpoint: $APPLICATION_ENDPOINT"
          popd         
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: tests/cypress
          spec: cypress/integration/${{ matrix.containers }}
          browser: chrome
          headless: true
          config: baseUrl=${{ env.APPLICATION_ENDPOINT }}
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots/
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: env.SLACK_WEBHOOK_URL != '' && contains(fromJson('["develop", "master", "production"]'), env.branch_name) && failure ()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{env.branch_name}} Deploy Failure
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_COLOR: ${{job.status}}
          SLACK_FOOTER: ""
          MSG_MINIMAL: actions url,commit,ref

  a11y-tests:
    name: A11y Tests
    needs: deploy
    if: ${{ github.ref != 'refs/heads/prod' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: 
          [
            homePage,
            AppendixKAmmendmentPage,
            CHIPSPAPage,
         #   dashboardPage,
            faqPage,
            manageProfilePage,
            MedicaidSpaPage,
            packagePageSpas,
            packagePageWaivers,
            RequestRoleChangePage,
            requestTempExtentionPage,
            RespondToCHIPSPAPage,
            RespondToMedicaidSpaTest,
            RespondToWaiverRaiPage,
            spaTypePage,
            submissionType,
            waiverActionPage,
            waiverActionTypePage,
          ]
    steps:
      - name: set branch_name
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: set branch specific variable names
        run: ./.github/build_vars.sh set_names
      - name: set variable values
        run: ./.github/build_vars.sh set_values
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_ACCESS_KEY_ID] || secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_SECRET_ACCESS_KEY] || secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_AWS_DEFAULT_REGION] || secrets.AWS_DEFAULT_REGION }}
          INFRASTRUCTURE_TYPE: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_INFRASTRUCTURE_TYPE] || secrets.INFRASTRUCTURE_TYPE || 'development' }}
          STAGE_PREFIX: ${{ secrets.STAGE_PREFIX }}
          COGNITO_TEST_USERS_PASSWORD: ${{ secrets[env.BRANCH_SPECIFIC_VARNAME_COGNITO_TEST_USERS_PASSWORD] || secrets.COGNITO_TEST_USERS_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Combine package-lock.json files to single file
        run: find services -maxdepth 3 -name package-lock.json | xargs cat package-lock.json > combined-package-lock.txt
      - name: cache service dependencies
        uses: actions/cache@v2
        with:
          path: |
            services/app-api/node_modules
            services/uploads/node_modules
            services/stream-functions/node_modules
            services/ui/node_modules
            services/ui-auth/node_modules
            services/ui-src/node_modules
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('combined-package-lock.txt') }}
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: Endpoint
        run: |
          pushd services
          export APPLICATION_ENDPOINT=`./output.sh ui ApplicationEndpointUrl $STAGE_PREFIX$branch_name`
          echo "APPLICATION_ENDPOINT=$APPLICATION_ENDPOINT" >> $GITHUB_ENV
          echo "Application endpoint: $APPLICATION_ENDPOINT"
          popd
      - name: Check Project A11y
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: tests/cypress
          spec: cypress/integration/a11y/${{ matrix.containers }}.spec.js
          browser: chrome
          headless: true
          config: baseUrl=${{ env.APPLICATION_ENDPOINT }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
